{% set name = "nengo-gui" %}
{% set version = "0.5.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/nengo-gui-{{ version }}.tar.gz
  sha256: 58ea7d7ff1a4aab60490d0af44459555c13672d213a8fd2090f6e259e7dbbc83
  patches:
    - fix-python-3-8-and-higher.patch

build:
  number: 1
  noarch: python
  entry_points:
    - nengo_gui = nengo_gui:old_main
    - nengo = nengo_gui:main
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - setuptools
    - python {{ python_min }}
  run:
    - nengo >=2.6.0
    - python >={{ python_min }},<3.11
    - jedi >=0.16.0

test:
  imports:
    - nengo_gui
    - nengo_gui._vendor
  commands:
    - pip check
    - nengo_gui --help
    - nengo --help
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/nengo/nengo-gui
  summary: Web-based GUI for building and visualizing Nengo models.
  license: LicenseRef-NENGO
  license_file: LICENSE.rst

extra:
  recipe-maintainers:
    - Tobias-Fischer
