{% set name = "nengo-gui" %}
{% set version = "0.4.9" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/nengo-gui-{{ version }}.tar.gz
  sha256: 47ede1644f4aa1e44b12a46c78c539a4496a91b3883cf80c1a66cce7c9e49a00
  patches:
    - fix-python-3-8-and-higher.patch

build:
  number: 0
  noarch: python
  entry_points:
    - nengo_gui = nengo_gui:old_main
    - nengo = nengo_gui:main
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - nengo >=2.6.0
    - python >=3.6
    - jedi >=0.16.0

test:
  imports:
    - nengo_gui
    - nengo_gui._vendor
  commands:
    - pip check
    - nengo_gui --help
    - nengo --help
  requires:
    - pip

about:
  home: https://github.com/nengo/nengo-gui
  summary: Web-based GUI for building and visualizing Nengo models.
  license: LicenseRef-NENGO
  license_file: LICENSE.rst

extra:
  recipe-maintainers:
    - Tobias-Fischer
